# SEO / <meta> tag information
title: The Resume of Kayla Lomas
description: Kayla Lomas is a hard worker, with a enthusiasm for customer service.
# theme color for header, borders, section headings
# For best results, choose a color that has a color ratio of at least 3.5
# against white. Otherwise, all text etc is set to black to preserve readability
# @link http://leaverou.github.io/contrast-ratio/
theme: '#009688'
# of work experiences to show
jobs: 3
# of educational experiences to show
schools: 1
# show 'References available' link in footer
references: true
# Remove theme color on print
printstyles: false
# Show promo link under resume (you probably want to set this to false)
promolink: true
